# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    variables:
    - group: 'Microservices Pipeline variables-devtest'
    displayName: Build job
    pool:
      vmImage: 'ubuntu-latest'


    steps:
    - task: DotNetCoreCLI@2
      displayName: Run all unittests in solution
      inputs:
        command: 'test'
        projects: '**/MicroserviceSolution.sln'
   
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: '**/AgentCallbackActor/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag) 
       
    - task: PublishPipelineArtifact@0
      inputs:
              targetPath: '$(Pipeline.Workspace)'

- stage: DeployToDev
  displayName: Deploy stage
  dependsOn: Build
  jobs:
  - deployment: Deploy
    variables:
    - group: 'Microservices Pipeline variables-devtest'
    displayName: Deploying to Development
    pool:
      name: 'PHP and Brandsites POOL'
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'    
              
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: $(k8sNamespace)
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection) 
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              manifests: |
                $(System.ArtifactsDirectory)/**/agentcallbackactor.deploy.yaml              
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

- stage: DeployToProd
  displayName: Deploy to prod
  dependsOn: DeployToDev
  jobs:
  - deployment: Deploy
    variables:
    - group: 'Microservices Pipeline variables-prod'
    displayName: Deploying to Production
    pool:
      name: 'PHP and Brandsites POOL'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@1
            inputs:
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'    
          
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              namespace: $(k8sNamespace)
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection) 
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              manifests: |
                $(System.ArtifactsDirectory)/**/agentcallbackactor.deployprod.yaml 
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
